### ISSUE TITLE
Issue title

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/experiments#13]
### Bashly Version

Latest Ruby Gem

### Description

asd

### Bashly.yml

```yaml
body:
  - type: dropdown
    id: version
    attributes:
      label: Bashly Version
      description: What version of bashly are you running?
      options:
```

### Reproduction Steps

asd

### Actual Behavior

asd

### Expected Behavior

asd
